
// User
export const GET_ALL_USER = 'GET_ALL_USER';
export const GET_ALL_USER_SUCCESS = 'GET_ALL_USER_SUCCESS';
export const ADD_USER = 'ADD_USER';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const EDIT_USER = 'EDIT_USER';
export const DELETE_USER = 'DELETE_USER';
export const HIDE_LOADING = 'HIDE_LOADING';

export const GET_ALL_REPORTTYPE = 'GET_ALL_REPORTTYPE';
export const GET_ALL_REPORTTYPE_SUCCESS = 'GET_ALL_REPORTTYPE_SUCCESS';
export const ADD_REPORTTYPE = 'ADD_REPORTTYPE';
export const ADD_REPORTTYPE_SUCCESS = 'ADD_REPORTTYPE_SUCCESS';
export const EDIT_REPORTTYPE = 'EDIT_REPORTTYPE';
export const DELETE_REPORTTYPE = 'DELETE_REPORTTYPE';
export const HIDE_LOADING_REPORTTYPE = 'HIDE_LOADING_REPORTTYPE';

export const GET_ALL_REPORT = 'GET_ALL_REPORT';
export const GET_ALL_REPORT_SUCCESS = 'GET_ALL_REPORT_SUCCESS';
export const ADD_REPORT = 'ADD_REPORT';
export const ADD_REPORT_SUCCESS = 'ADD_REPORT_SUCCESS';
export const EDIT_REPORT = 'EDIT_REPORT';
export const DELETE_REPORT = 'DELETE_REPORT';
export const HIDE_LOADING_REPORT = 'HIDE_LOADING_REPORT';

export const GET_ALL_POST = 'GET_ALL_POST';
export const GET_ALL_POST_SUCCESS = 'GET_ALL_POST_SUCCESS';
export const ADD_POST = 'ADD_POST';
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';
export const EDIT_POST = 'EDIT_POST';
export const DELETE_POST = 'DELETE_POST';
export const HIDE_LOADING_POST = 'HIDE_LOADING_POST';

export const GET_ALL_COMMENT = 'GET_ALL_COMMENT';
export const GET_ALL_COMMENT_SUCCESS = 'GET_ALL_COMMENT_SUCCESS';
export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const EDIT_COMMENT = 'EDIT_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const HIDE_LOADING_COMMENT = 'HIDE_LOADING_COMMENT';

export const GET_ALL_POSTSTYLE = 'GET_ALL_POSTSTYLE';
export const GET_ALL_POSTSTYLE_SUCCESS = 'GET_ALL_POSTSTYLE_SUCCESS';
export const ADD_POSTSTYLE = 'ADD_POSTSTYLE';
export const ADD_POSTSTYLE_SUCCESS = 'ADD_POSTSTYLE_SUCCESS';
export const EDIT_POSTSTYLE = 'EDIT_POSTSTYLE';
export const DELETE_POSTSTYLE = 'DELETE_POSTSTYLE';
export const HIDE_LOADING_POSTSTYLE = 'HIDE_LOADING_POSTSTYLE';

export const GET_ALL_NOTIFY = 'GET_ALL_NOTIFY';
export const GET_ALL_NOTIFY_SUCCESS = 'GET_ALL_NOTIFY_SUCCESS';
export const ADD_NOTIFY = 'ADD_NOTIFY';
export const ADD_NOTIFY_SUCCESS = 'ADD_NOTIFY_SUCCESS';
export const EDIT_NOTIFY = 'EDIT_NOTIFY';
export const DELETE_NOTIFY = 'DELETE_NOTIFY';
export const HIDE_LOADING_NOTIFY = 'HIDE_LOADING_NOTIFY';

